### ISSUE TITLE
Same less version as Firefly

### ISSUE THREAD

**Issue by roobottom** [fireflylearning/pattern-library#144]
Firefly uses [dotless](https://github.com/dotless/dotless), which, [as far as I can tell](https://github.com/dotless/dotless/issues/457), uses someting like v1.5.0 of less. Maybe we should downgrade the pattern library to use this same version in order to prevent writing code in the pattern library that subsequently breaks in Firefly.

In an ideal world we'd find a new less processor solution for Firefly that tracks the latest version of less.

**Comment by dkhuntrods** [comment]
Webapp will have its version of the less compiler updated

**Comment by dkhuntrods** [comment]
Webapp is having is less compiler updated
