### ISSUE TITLE
Including raw HTML when using variables

### ISSUE THREAD

**Issue by mwilliamson-firefly** [fireflylearning/pattern-library#59]
At the moment, we include raw HTML with something like:

``` xsl
<xsl:value-of="html" disable-output-escaping="yes"/>
```

Unfortunately, `disable-output-escaping` is a bit of a hack: rather than turning that into a bunch of nodes, it's still just a string with a hint to the serializer not to both escaping it. That hint is lost as the nodes are passed around through variables and further templates. A better solution is to turn the HTML into actual nodes, by doing one of:
- Ensure that Firefly always outputs valid XML when including HTML, and that it's actually included as XML nodes rather than a string. This is simplest, but might mean needing to duplicating content since some existing templates rely on the HTML being a string rather XML nodes i.e. we'll need to provide both.
- Add an extension that turns a string into XML. This might change the output slightly since it will need to be well-formed XML, but in practice I think this should be fine. I'm not sure how this would work with whatever C library (libxml2?) has been playing with. I might suggest that, if possible, we just use one XSL engine for both the pattern library and Firefly i.e. use the engine in .NET, which both allows us to write extensions in one way, and also means that the behaviour is more likely to be consistent.
- Write an XSL template that can turn XML strings into actual nodes. I suspect this is rather ill-advised.
- Something I haven't thought of.

**Comment by AdamLynamFirefly** [comment]
The problem with this issue is that it feels like there is not actually a good answer; just a handful of ones with varying degrees of badness. It seems like a red flag to me, like maybe we are doing something fundamentally wrong.

**Comment by mwilliamson-firefly** [comment]
Since we still need to support multiple engines, we've decided that the simplest thing to do is to require the input XML to contain the XML as a bunch of nodes rather than as a flat string.
