### ISSUE TITLE
Could this live inside the Firefly repository?

### ISSUE THREAD

**Issue by mwilliamson-firefly** [fireflylearning/pattern-library#61]
At the moment, it's not clear what version of the pattern library is in a given version of Firefly. Could the pattern library live in the same repo, or at least be a git submodule so that it's unambiguous? If we did so, it might also be worth considering adding the compiled copy of the pattern library to the git ignores.

**Comment by dkhuntrods** [comment]
I don't think having it live within the webapp fits very well with the core concept of the pattern library, but a submodule would be fine. Fundamentally, we want to keep it as a separate tool, independent (as possible) of whatever's used on the backend. 

It also means we can keep it as public repo, which has a variety of benefits. 

We could also additionally have release branches that track the Firefly webapp versions.

**Comment by mwilliamson-firefly** [comment]
A submodule would be fine by me, so long as everyone is happy dealing with git submodules, and we don't store the compiled output in git (to make sure that a commit doesn't contain an outdated pattern library).

> It also means we can keep it as public repo, which has a variety of benefits. 

Mind if I ask what those benefits are?

**Comment by roobottom** [comment]
I like the idea of the compiled copy — alternate proposal is to have a hosted copy of the pattern library (possibly spat out by a build server somewhere) that everyone can access for reference. Github pages maybe?

The public repo thing:
- It allows third party forks
- It's a great recruitment tool "look at the cool tools we use at Firefly"
- It keeps us honest
- It's a way to be part of a wider community of developers without exposing our core code.

**Comment by mwilliamson-firefly** [comment]
If we want the compiled copy so somebody can access it easily, I'm happy for it to be uploaded somewhere. Alternatively, we could add a check on Jenkins or whatever that the checked-in copy is up-to-date, but that still means a lot of noise in git, which I'd be keen to avoid if possible.

**Comment by roobottom** [comment]
Not sure what you mean by noise in git? In terms of having an extra repo for the compiled version?

**Comment by mwilliamson-firefly** [comment]
If we kept the compiled output in the main Firefly repository, then each time we updated the pattern library, you'd see the diff for the compiled output, which we wouldn't really care about.

**Comment by roobottom** [comment]
I'm suggesting that it lives in a `gh-pages` branch — that wouldn't cause the same diffing problems would it?

**Comment by mwilliamson-firefly** [comment]
Nope, that would be absolutely fine with me.

**Comment by AdamLynamFirefly** [comment]
I am finding it difficult to phrase what I am thinking. But it seems really odd to me that something that is so fundamentally a part of Firefly, the user interface, is being treated in such a detached way.

I am not really suggesting that including pre-compiled patterns is wrong, but it feels like the UI is more distant this way.

To me it feels very natural for the pattern library to be part of Firefly itself.

**Comment by roobottom** [comment]
Agree in general, however the original purpose behind the pattern lib was to give us a clean environment in which to build and test patterns. This also has the benefit that anyone can develop for the pattern library directly on a mac without any VM nastyness clogging up their development pipes, as it were.

Does a sub-module not solve this for you? I'd be interested to know what benefits we get from making the pattern library part of the `firefly-webapp` project?

We'd still have to run a build process, although I guess this _could_ be done as part of the general build process of Firefly. 

I can see both sides here, so I'm keen we make a decision based on the greater good.

**Comment by AdamLynamFirefly** [comment]
> This also has the benefit that anyone can develop for the pattern library directly on a mac without any VM nastyness clogging up their development pipes, as it were.

I don't think we should make a decision about this based on the complexity of the development environment; the better argument would be that the pattern library should be stand alone because there is value in running it separately. If working on Windows is a genuine problem, we should really be addressing that directly instead.

> Does a sub-module not solve this for you? I'd be interested to know what benefits we get from making the pattern library part of the firefly-webapp project?

The submodule works... but there is a funny sense of ownership around a submodule. I am probably not seeing the big picture here; but the contents of the pattern library feel very specifically a core part of Firefly. More so than other bits, like the cloud uploader, and other plugins, and they are in the main repository.

> We'd still have to run a build process, although I guess this could be done as part of the general build process of Firefly.

This feels like a positive to me. The pattern library is currently awkward to keep up to date as a separate project.

I don't really have a compelling argument, it just feels natural to be in the same place. :D
