### ISSUE TITLE
Simplify React components

### ISSUE THREAD

**Issue by mwilliamson-firefly** [fireflylearning/pattern-library#65]
I think we've probably pushed a bit too much logic into the React components in the pattern library. To borrow [some parlance from the React community](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.wy6tjij6c), things in the pattern library should just be presentational components, which should simplify things. To quote, presentational components:
- Are concerned with how things look.
- May contain both presentational and container components*\* inside, and usually have some DOM markup and styles of their own.
- Often allow containment via this.props.children.
- Have no dependencies on the rest of the app, such as Flux actions or stores.
- Don’t specify how the data is loaded or mutated.
- Receive data and callbacks exclusively via props.
- Rarely have their own state (when they do, it’s UI state rather than data).
- Are written as functional components unless they need state, lifecycle hooks, or performance optimizations.
- Examples: Page, Sidebar, Story, UserInfo, List.

(I'd suggest reading the rest of the linked post as well.)

To take an example, this would mean the recipient picker would have no notion of how it finds principals, nor would it be responsible for updating any state. Instead, it just knows the list of current recipients, the current search and any results, all passed in through `props`. When the user types or selects a recipient or whatever, it calls a callback, also passed in through `props`.

In Firefly, we could then create a container component that would wire up the recipient picker with the relevant bits of state and AJAX calls.

**Comment by dkhuntrods** [comment]
Closing as we're now following this approach.
